//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationMVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.Drawing;

    public partial class Customer
    {
        public int Id { get; set; }
        public string name { get; set; }
        public string motto { get; set; }
        public string blog { get; set; }
        public string hometown { get; set; }
    }
}
